apiVersion: v1
kind: Service
metadata:
  name: {{ include "kube-sentinel.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "kube-sentinel.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
      protocol: TCP
      name: metrics
  selector:
    app: {{ include "kube-sentinel.fullname" . }}
